// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jpmorganchase/quorum-account-plugin-sdk-go/proto (interfaces: AccountServiceClient)

// Package mock_proto is a generated GoMock package.
package mock_proto

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	proto "github.com/jpmorganchase/quorum-account-plugin-sdk-go/proto"
	grpc "google.golang.org/grpc"
)

// MockAccountServiceClient is a mock of AccountServiceClient interface
type MockAccountServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockAccountServiceClientMockRecorder
}

// MockAccountServiceClientMockRecorder is the mock recorder for MockAccountServiceClient
type MockAccountServiceClientMockRecorder struct {
	mock *MockAccountServiceClient
}

// NewMockAccountServiceClient creates a new mock instance
func NewMockAccountServiceClient(ctrl *gomock.Controller) *MockAccountServiceClient {
	mock := &MockAccountServiceClient{ctrl: ctrl}
	mock.recorder = &MockAccountServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAccountServiceClient) EXPECT() *MockAccountServiceClientMockRecorder {
	return m.recorder
}

// Accounts mocks base method
func (m *MockAccountServiceClient) Accounts(arg0 context.Context, arg1 *proto.AccountsRequest, arg2 ...grpc.CallOption) (*proto.AccountsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Accounts", varargs...)
	ret0, _ := ret[0].(*proto.AccountsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Accounts indicates an expected call of Accounts
func (mr *MockAccountServiceClientMockRecorder) Accounts(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accounts", reflect.TypeOf((*MockAccountServiceClient)(nil).Accounts), varargs...)
}

// Close mocks base method
func (m *MockAccountServiceClient) Close(arg0 context.Context, arg1 *proto.CloseRequest, arg2 ...grpc.CallOption) (*proto.CloseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Close", varargs...)
	ret0, _ := ret[0].(*proto.CloseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Close indicates an expected call of Close
func (mr *MockAccountServiceClientMockRecorder) Close(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAccountServiceClient)(nil).Close), varargs...)
}

// Contains mocks base method
func (m *MockAccountServiceClient) Contains(arg0 context.Context, arg1 *proto.ContainsRequest, arg2 ...grpc.CallOption) (*proto.ContainsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Contains", varargs...)
	ret0, _ := ret[0].(*proto.ContainsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Contains indicates an expected call of Contains
func (mr *MockAccountServiceClientMockRecorder) Contains(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Contains", reflect.TypeOf((*MockAccountServiceClient)(nil).Contains), varargs...)
}

// ImportRawKey mocks base method
func (m *MockAccountServiceClient) ImportRawKey(arg0 context.Context, arg1 *proto.ImportRawKeyRequest, arg2 ...grpc.CallOption) (*proto.ImportRawKeyResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ImportRawKey", varargs...)
	ret0, _ := ret[0].(*proto.ImportRawKeyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportRawKey indicates an expected call of ImportRawKey
func (mr *MockAccountServiceClientMockRecorder) ImportRawKey(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportRawKey", reflect.TypeOf((*MockAccountServiceClient)(nil).ImportRawKey), varargs...)
}

// Lock mocks base method
func (m *MockAccountServiceClient) Lock(arg0 context.Context, arg1 *proto.LockRequest, arg2 ...grpc.CallOption) (*proto.LockResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Lock", varargs...)
	ret0, _ := ret[0].(*proto.LockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lock indicates an expected call of Lock
func (mr *MockAccountServiceClientMockRecorder) Lock(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lock", reflect.TypeOf((*MockAccountServiceClient)(nil).Lock), varargs...)
}

// NewAccount mocks base method
func (m *MockAccountServiceClient) NewAccount(arg0 context.Context, arg1 *proto.NewAccountRequest, arg2 ...grpc.CallOption) (*proto.NewAccountResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewAccount", varargs...)
	ret0, _ := ret[0].(*proto.NewAccountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewAccount indicates an expected call of NewAccount
func (mr *MockAccountServiceClientMockRecorder) NewAccount(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewAccount", reflect.TypeOf((*MockAccountServiceClient)(nil).NewAccount), varargs...)
}

// Open mocks base method
func (m *MockAccountServiceClient) Open(arg0 context.Context, arg1 *proto.OpenRequest, arg2 ...grpc.CallOption) (*proto.OpenResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Open", varargs...)
	ret0, _ := ret[0].(*proto.OpenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open
func (mr *MockAccountServiceClientMockRecorder) Open(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockAccountServiceClient)(nil).Open), varargs...)
}

// Sign mocks base method
func (m *MockAccountServiceClient) Sign(arg0 context.Context, arg1 *proto.SignRequest, arg2 ...grpc.CallOption) (*proto.SignResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Sign", varargs...)
	ret0, _ := ret[0].(*proto.SignResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sign indicates an expected call of Sign
func (mr *MockAccountServiceClientMockRecorder) Sign(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sign", reflect.TypeOf((*MockAccountServiceClient)(nil).Sign), varargs...)
}

// Status mocks base method
func (m *MockAccountServiceClient) Status(arg0 context.Context, arg1 *proto.StatusRequest, arg2 ...grpc.CallOption) (*proto.StatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Status", varargs...)
	ret0, _ := ret[0].(*proto.StatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status
func (mr *MockAccountServiceClientMockRecorder) Status(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockAccountServiceClient)(nil).Status), varargs...)
}

// TimedUnlock mocks base method
func (m *MockAccountServiceClient) TimedUnlock(arg0 context.Context, arg1 *proto.TimedUnlockRequest, arg2 ...grpc.CallOption) (*proto.TimedUnlockResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TimedUnlock", varargs...)
	ret0, _ := ret[0].(*proto.TimedUnlockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TimedUnlock indicates an expected call of TimedUnlock
func (mr *MockAccountServiceClientMockRecorder) TimedUnlock(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TimedUnlock", reflect.TypeOf((*MockAccountServiceClient)(nil).TimedUnlock), varargs...)
}

// UnlockAndSign mocks base method
func (m *MockAccountServiceClient) UnlockAndSign(arg0 context.Context, arg1 *proto.UnlockAndSignRequest, arg2 ...grpc.CallOption) (*proto.SignResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UnlockAndSign", varargs...)
	ret0, _ := ret[0].(*proto.SignResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnlockAndSign indicates an expected call of UnlockAndSign
func (mr *MockAccountServiceClientMockRecorder) UnlockAndSign(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockAndSign", reflect.TypeOf((*MockAccountServiceClient)(nil).UnlockAndSign), varargs...)
}
