// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package proto

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetEventStreamResponse_Event int32

const (
	GetEventStreamResponse_WALLET_ARRIVED GetEventStreamResponse_Event = 0
	GetEventStreamResponse_WALLET_OPENED  GetEventStreamResponse_Event = 1
	GetEventStreamResponse_WALLET_DROPPED GetEventStreamResponse_Event = 2
	GetEventStreamResponse_PLUGIN_STARTED GetEventStreamResponse_Event = 3
)

var GetEventStreamResponse_Event_name = map[int32]string{
	0: "WALLET_ARRIVED",
	1: "WALLET_OPENED",
	2: "WALLET_DROPPED",
	3: "PLUGIN_STARTED",
}

var GetEventStreamResponse_Event_value = map[string]int32{
	"WALLET_ARRIVED": 0,
	"WALLET_OPENED":  1,
	"WALLET_DROPPED": 2,
	"PLUGIN_STARTED": 3,
}

func (x GetEventStreamResponse_Event) String() string {
	return proto.EnumName(GetEventStreamResponse_Event_name, int32(x))
}

func (GetEventStreamResponse_Event) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{18, 0}
}

type Account struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Account) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type StatusRequest struct {
	WalletUrl            string   `protobuf:"bytes,1,opt,name=walletUrl,proto3" json:"walletUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (m *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(m, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

func (m *StatusRequest) GetWalletUrl() string {
	if m != nil {
		return m.WalletUrl
	}
	return ""
}

type StatusResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type OpenRequest struct {
	WalletUrl            string   `protobuf:"bytes,1,opt,name=walletUrl,proto3" json:"walletUrl,omitempty"`
	Passphrase           string   `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenRequest) Reset()         { *m = OpenRequest{} }
func (m *OpenRequest) String() string { return proto.CompactTextString(m) }
func (*OpenRequest) ProtoMessage()    {}
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{3}
}

func (m *OpenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenRequest.Unmarshal(m, b)
}
func (m *OpenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenRequest.Marshal(b, m, deterministic)
}
func (m *OpenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenRequest.Merge(m, src)
}
func (m *OpenRequest) XXX_Size() int {
	return xxx_messageInfo_OpenRequest.Size(m)
}
func (m *OpenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenRequest proto.InternalMessageInfo

func (m *OpenRequest) GetWalletUrl() string {
	if m != nil {
		return m.WalletUrl
	}
	return ""
}

func (m *OpenRequest) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

type OpenResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenResponse) Reset()         { *m = OpenResponse{} }
func (m *OpenResponse) String() string { return proto.CompactTextString(m) }
func (*OpenResponse) ProtoMessage()    {}
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{4}
}

func (m *OpenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenResponse.Unmarshal(m, b)
}
func (m *OpenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenResponse.Marshal(b, m, deterministic)
}
func (m *OpenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenResponse.Merge(m, src)
}
func (m *OpenResponse) XXX_Size() int {
	return xxx_messageInfo_OpenResponse.Size(m)
}
func (m *OpenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OpenResponse proto.InternalMessageInfo

type CloseRequest struct {
	WalletUrl            string   `protobuf:"bytes,1,opt,name=walletUrl,proto3" json:"walletUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseRequest) Reset()         { *m = CloseRequest{} }
func (m *CloseRequest) String() string { return proto.CompactTextString(m) }
func (*CloseRequest) ProtoMessage()    {}
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{5}
}

func (m *CloseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseRequest.Unmarshal(m, b)
}
func (m *CloseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseRequest.Marshal(b, m, deterministic)
}
func (m *CloseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseRequest.Merge(m, src)
}
func (m *CloseRequest) XXX_Size() int {
	return xxx_messageInfo_CloseRequest.Size(m)
}
func (m *CloseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseRequest proto.InternalMessageInfo

func (m *CloseRequest) GetWalletUrl() string {
	if m != nil {
		return m.WalletUrl
	}
	return ""
}

type CloseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseResponse) Reset()         { *m = CloseResponse{} }
func (m *CloseResponse) String() string { return proto.CompactTextString(m) }
func (*CloseResponse) ProtoMessage()    {}
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{6}
}

func (m *CloseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseResponse.Unmarshal(m, b)
}
func (m *CloseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseResponse.Marshal(b, m, deterministic)
}
func (m *CloseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseResponse.Merge(m, src)
}
func (m *CloseResponse) XXX_Size() int {
	return xxx_messageInfo_CloseResponse.Size(m)
}
func (m *CloseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloseResponse proto.InternalMessageInfo

type AccountsRequest struct {
	WalletUrl            string   `protobuf:"bytes,1,opt,name=walletUrl,proto3" json:"walletUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountsRequest) Reset()         { *m = AccountsRequest{} }
func (m *AccountsRequest) String() string { return proto.CompactTextString(m) }
func (*AccountsRequest) ProtoMessage()    {}
func (*AccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{7}
}

func (m *AccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountsRequest.Unmarshal(m, b)
}
func (m *AccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountsRequest.Marshal(b, m, deterministic)
}
func (m *AccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountsRequest.Merge(m, src)
}
func (m *AccountsRequest) XXX_Size() int {
	return xxx_messageInfo_AccountsRequest.Size(m)
}
func (m *AccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountsRequest proto.InternalMessageInfo

func (m *AccountsRequest) GetWalletUrl() string {
	if m != nil {
		return m.WalletUrl
	}
	return ""
}

type AccountsResponse struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AccountsResponse) Reset()         { *m = AccountsResponse{} }
func (m *AccountsResponse) String() string { return proto.CompactTextString(m) }
func (*AccountsResponse) ProtoMessage()    {}
func (*AccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{8}
}

func (m *AccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountsResponse.Unmarshal(m, b)
}
func (m *AccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountsResponse.Marshal(b, m, deterministic)
}
func (m *AccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountsResponse.Merge(m, src)
}
func (m *AccountsResponse) XXX_Size() int {
	return xxx_messageInfo_AccountsResponse.Size(m)
}
func (m *AccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountsResponse proto.InternalMessageInfo

func (m *AccountsResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type ContainsRequest struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainsRequest) Reset()         { *m = ContainsRequest{} }
func (m *ContainsRequest) String() string { return proto.CompactTextString(m) }
func (*ContainsRequest) ProtoMessage()    {}
func (*ContainsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{9}
}

func (m *ContainsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainsRequest.Unmarshal(m, b)
}
func (m *ContainsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainsRequest.Marshal(b, m, deterministic)
}
func (m *ContainsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainsRequest.Merge(m, src)
}
func (m *ContainsRequest) XXX_Size() int {
	return xxx_messageInfo_ContainsRequest.Size(m)
}
func (m *ContainsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContainsRequest proto.InternalMessageInfo

func (m *ContainsRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type ContainsResponse struct {
	IsContained          bool     `protobuf:"varint,1,opt,name=isContained,proto3" json:"isContained,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainsResponse) Reset()         { *m = ContainsResponse{} }
func (m *ContainsResponse) String() string { return proto.CompactTextString(m) }
func (*ContainsResponse) ProtoMessage()    {}
func (*ContainsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{10}
}

func (m *ContainsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainsResponse.Unmarshal(m, b)
}
func (m *ContainsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainsResponse.Marshal(b, m, deterministic)
}
func (m *ContainsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainsResponse.Merge(m, src)
}
func (m *ContainsResponse) XXX_Size() int {
	return xxx_messageInfo_ContainsResponse.Size(m)
}
func (m *ContainsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContainsResponse proto.InternalMessageInfo

func (m *ContainsResponse) GetIsContained() bool {
	if m != nil {
		return m.IsContained
	}
	return false
}

type SignHashRequest struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Hash                 []byte   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignHashRequest) Reset()         { *m = SignHashRequest{} }
func (m *SignHashRequest) String() string { return proto.CompactTextString(m) }
func (*SignHashRequest) ProtoMessage()    {}
func (*SignHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{11}
}

func (m *SignHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignHashRequest.Unmarshal(m, b)
}
func (m *SignHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignHashRequest.Marshal(b, m, deterministic)
}
func (m *SignHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignHashRequest.Merge(m, src)
}
func (m *SignHashRequest) XXX_Size() int {
	return xxx_messageInfo_SignHashRequest.Size(m)
}
func (m *SignHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignHashRequest proto.InternalMessageInfo

func (m *SignHashRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *SignHashRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type SignHashResponse struct {
	Result               []byte   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignHashResponse) Reset()         { *m = SignHashResponse{} }
func (m *SignHashResponse) String() string { return proto.CompactTextString(m) }
func (*SignHashResponse) ProtoMessage()    {}
func (*SignHashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{12}
}

func (m *SignHashResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignHashResponse.Unmarshal(m, b)
}
func (m *SignHashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignHashResponse.Marshal(b, m, deterministic)
}
func (m *SignHashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignHashResponse.Merge(m, src)
}
func (m *SignHashResponse) XXX_Size() int {
	return xxx_messageInfo_SignHashResponse.Size(m)
}
func (m *SignHashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignHashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignHashResponse proto.InternalMessageInfo

func (m *SignHashResponse) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

type SignTxRequest struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	RlpTx                []byte   `protobuf:"bytes,2,opt,name=rlpTx,proto3" json:"rlpTx,omitempty"`
	ChainID              []byte   `protobuf:"bytes,3,opt,name=chainID,proto3" json:"chainID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignTxRequest) Reset()         { *m = SignTxRequest{} }
func (m *SignTxRequest) String() string { return proto.CompactTextString(m) }
func (*SignTxRequest) ProtoMessage()    {}
func (*SignTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{13}
}

func (m *SignTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignTxRequest.Unmarshal(m, b)
}
func (m *SignTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignTxRequest.Marshal(b, m, deterministic)
}
func (m *SignTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignTxRequest.Merge(m, src)
}
func (m *SignTxRequest) XXX_Size() int {
	return xxx_messageInfo_SignTxRequest.Size(m)
}
func (m *SignTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignTxRequest proto.InternalMessageInfo

func (m *SignTxRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *SignTxRequest) GetRlpTx() []byte {
	if m != nil {
		return m.RlpTx
	}
	return nil
}

func (m *SignTxRequest) GetChainID() []byte {
	if m != nil {
		return m.ChainID
	}
	return nil
}

type SignTxResponse struct {
	RlpTx                []byte   `protobuf:"bytes,1,opt,name=rlpTx,proto3" json:"rlpTx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignTxResponse) Reset()         { *m = SignTxResponse{} }
func (m *SignTxResponse) String() string { return proto.CompactTextString(m) }
func (*SignTxResponse) ProtoMessage()    {}
func (*SignTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{14}
}

func (m *SignTxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignTxResponse.Unmarshal(m, b)
}
func (m *SignTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignTxResponse.Marshal(b, m, deterministic)
}
func (m *SignTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignTxResponse.Merge(m, src)
}
func (m *SignTxResponse) XXX_Size() int {
	return xxx_messageInfo_SignTxResponse.Size(m)
}
func (m *SignTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignTxResponse proto.InternalMessageInfo

func (m *SignTxResponse) GetRlpTx() []byte {
	if m != nil {
		return m.RlpTx
	}
	return nil
}

type SignHashWithPassphraseRequest struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Hash                 []byte   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Passphrase           string   `protobuf:"bytes,3,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignHashWithPassphraseRequest) Reset()         { *m = SignHashWithPassphraseRequest{} }
func (m *SignHashWithPassphraseRequest) String() string { return proto.CompactTextString(m) }
func (*SignHashWithPassphraseRequest) ProtoMessage()    {}
func (*SignHashWithPassphraseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{15}
}

func (m *SignHashWithPassphraseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignHashWithPassphraseRequest.Unmarshal(m, b)
}
func (m *SignHashWithPassphraseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignHashWithPassphraseRequest.Marshal(b, m, deterministic)
}
func (m *SignHashWithPassphraseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignHashWithPassphraseRequest.Merge(m, src)
}
func (m *SignHashWithPassphraseRequest) XXX_Size() int {
	return xxx_messageInfo_SignHashWithPassphraseRequest.Size(m)
}
func (m *SignHashWithPassphraseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignHashWithPassphraseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignHashWithPassphraseRequest proto.InternalMessageInfo

func (m *SignHashWithPassphraseRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *SignHashWithPassphraseRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *SignHashWithPassphraseRequest) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

type SignTxWithPassphraseRequest struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	RlpTx                []byte   `protobuf:"bytes,2,opt,name=rlpTx,proto3" json:"rlpTx,omitempty"`
	ChainID              []byte   `protobuf:"bytes,3,opt,name=chainID,proto3" json:"chainID,omitempty"`
	Passphrase           string   `protobuf:"bytes,4,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignTxWithPassphraseRequest) Reset()         { *m = SignTxWithPassphraseRequest{} }
func (m *SignTxWithPassphraseRequest) String() string { return proto.CompactTextString(m) }
func (*SignTxWithPassphraseRequest) ProtoMessage()    {}
func (*SignTxWithPassphraseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{16}
}

func (m *SignTxWithPassphraseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignTxWithPassphraseRequest.Unmarshal(m, b)
}
func (m *SignTxWithPassphraseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignTxWithPassphraseRequest.Marshal(b, m, deterministic)
}
func (m *SignTxWithPassphraseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignTxWithPassphraseRequest.Merge(m, src)
}
func (m *SignTxWithPassphraseRequest) XXX_Size() int {
	return xxx_messageInfo_SignTxWithPassphraseRequest.Size(m)
}
func (m *SignTxWithPassphraseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignTxWithPassphraseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignTxWithPassphraseRequest proto.InternalMessageInfo

func (m *SignTxWithPassphraseRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *SignTxWithPassphraseRequest) GetRlpTx() []byte {
	if m != nil {
		return m.RlpTx
	}
	return nil
}

func (m *SignTxWithPassphraseRequest) GetChainID() []byte {
	if m != nil {
		return m.ChainID
	}
	return nil
}

func (m *SignTxWithPassphraseRequest) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

type GetEventStreamRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventStreamRequest) Reset()         { *m = GetEventStreamRequest{} }
func (m *GetEventStreamRequest) String() string { return proto.CompactTextString(m) }
func (*GetEventStreamRequest) ProtoMessage()    {}
func (*GetEventStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{17}
}

func (m *GetEventStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventStreamRequest.Unmarshal(m, b)
}
func (m *GetEventStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventStreamRequest.Marshal(b, m, deterministic)
}
func (m *GetEventStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventStreamRequest.Merge(m, src)
}
func (m *GetEventStreamRequest) XXX_Size() int {
	return xxx_messageInfo_GetEventStreamRequest.Size(m)
}
func (m *GetEventStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventStreamRequest proto.InternalMessageInfo

type GetEventStreamResponse struct {
	Event                GetEventStreamResponse_Event `protobuf:"varint,1,opt,name=event,proto3,enum=proto.GetEventStreamResponse_Event" json:"event,omitempty"`
	WalletUrl            string                       `protobuf:"bytes,2,opt,name=walletUrl,proto3" json:"walletUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *GetEventStreamResponse) Reset()         { *m = GetEventStreamResponse{} }
func (m *GetEventStreamResponse) String() string { return proto.CompactTextString(m) }
func (*GetEventStreamResponse) ProtoMessage()    {}
func (*GetEventStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{18}
}

func (m *GetEventStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventStreamResponse.Unmarshal(m, b)
}
func (m *GetEventStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventStreamResponse.Marshal(b, m, deterministic)
}
func (m *GetEventStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventStreamResponse.Merge(m, src)
}
func (m *GetEventStreamResponse) XXX_Size() int {
	return xxx_messageInfo_GetEventStreamResponse.Size(m)
}
func (m *GetEventStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventStreamResponse proto.InternalMessageInfo

func (m *GetEventStreamResponse) GetEvent() GetEventStreamResponse_Event {
	if m != nil {
		return m.Event
	}
	return GetEventStreamResponse_WALLET_ARRIVED
}

func (m *GetEventStreamResponse) GetWalletUrl() string {
	if m != nil {
		return m.WalletUrl
	}
	return ""
}

type TimedUnlockRequest struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Duration             int64    `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimedUnlockRequest) Reset()         { *m = TimedUnlockRequest{} }
func (m *TimedUnlockRequest) String() string { return proto.CompactTextString(m) }
func (*TimedUnlockRequest) ProtoMessage()    {}
func (*TimedUnlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{19}
}

func (m *TimedUnlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimedUnlockRequest.Unmarshal(m, b)
}
func (m *TimedUnlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimedUnlockRequest.Marshal(b, m, deterministic)
}
func (m *TimedUnlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimedUnlockRequest.Merge(m, src)
}
func (m *TimedUnlockRequest) XXX_Size() int {
	return xxx_messageInfo_TimedUnlockRequest.Size(m)
}
func (m *TimedUnlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TimedUnlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TimedUnlockRequest proto.InternalMessageInfo

func (m *TimedUnlockRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *TimedUnlockRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *TimedUnlockRequest) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

type TimedUnlockResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimedUnlockResponse) Reset()         { *m = TimedUnlockResponse{} }
func (m *TimedUnlockResponse) String() string { return proto.CompactTextString(m) }
func (*TimedUnlockResponse) ProtoMessage()    {}
func (*TimedUnlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{20}
}

func (m *TimedUnlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimedUnlockResponse.Unmarshal(m, b)
}
func (m *TimedUnlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimedUnlockResponse.Marshal(b, m, deterministic)
}
func (m *TimedUnlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimedUnlockResponse.Merge(m, src)
}
func (m *TimedUnlockResponse) XXX_Size() int {
	return xxx_messageInfo_TimedUnlockResponse.Size(m)
}
func (m *TimedUnlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TimedUnlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TimedUnlockResponse proto.InternalMessageInfo

type LockRequest struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockRequest) Reset()         { *m = LockRequest{} }
func (m *LockRequest) String() string { return proto.CompactTextString(m) }
func (*LockRequest) ProtoMessage()    {}
func (*LockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{21}
}

func (m *LockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockRequest.Unmarshal(m, b)
}
func (m *LockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockRequest.Marshal(b, m, deterministic)
}
func (m *LockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockRequest.Merge(m, src)
}
func (m *LockRequest) XXX_Size() int {
	return xxx_messageInfo_LockRequest.Size(m)
}
func (m *LockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LockRequest proto.InternalMessageInfo

func (m *LockRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type LockResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockResponse) Reset()         { *m = LockResponse{} }
func (m *LockResponse) String() string { return proto.CompactTextString(m) }
func (*LockResponse) ProtoMessage()    {}
func (*LockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{22}
}

func (m *LockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockResponse.Unmarshal(m, b)
}
func (m *LockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockResponse.Marshal(b, m, deterministic)
}
func (m *LockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockResponse.Merge(m, src)
}
func (m *LockResponse) XXX_Size() int {
	return xxx_messageInfo_LockResponse.Size(m)
}
func (m *LockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LockResponse proto.InternalMessageInfo

type NewAccountRequest struct {
	NewAccountConfig     []byte   `protobuf:"bytes,1,opt,name=newAccountConfig,proto3" json:"newAccountConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewAccountRequest) Reset()         { *m = NewAccountRequest{} }
func (m *NewAccountRequest) String() string { return proto.CompactTextString(m) }
func (*NewAccountRequest) ProtoMessage()    {}
func (*NewAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{23}
}

func (m *NewAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewAccountRequest.Unmarshal(m, b)
}
func (m *NewAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewAccountRequest.Marshal(b, m, deterministic)
}
func (m *NewAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewAccountRequest.Merge(m, src)
}
func (m *NewAccountRequest) XXX_Size() int {
	return xxx_messageInfo_NewAccountRequest.Size(m)
}
func (m *NewAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewAccountRequest proto.InternalMessageInfo

func (m *NewAccountRequest) GetNewAccountConfig() []byte {
	if m != nil {
		return m.NewAccountConfig
	}
	return nil
}

type NewAccountResponse struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewAccountResponse) Reset()         { *m = NewAccountResponse{} }
func (m *NewAccountResponse) String() string { return proto.CompactTextString(m) }
func (*NewAccountResponse) ProtoMessage()    {}
func (*NewAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{24}
}

func (m *NewAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewAccountResponse.Unmarshal(m, b)
}
func (m *NewAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewAccountResponse.Marshal(b, m, deterministic)
}
func (m *NewAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewAccountResponse.Merge(m, src)
}
func (m *NewAccountResponse) XXX_Size() int {
	return xxx_messageInfo_NewAccountResponse.Size(m)
}
func (m *NewAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewAccountResponse proto.InternalMessageInfo

func (m *NewAccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type ImportRawKeyRequest struct {
	RawKey               string   `protobuf:"bytes,1,opt,name=rawKey,proto3" json:"rawKey,omitempty"`
	NewAccountConfig     []byte   `protobuf:"bytes,2,opt,name=newAccountConfig,proto3" json:"newAccountConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportRawKeyRequest) Reset()         { *m = ImportRawKeyRequest{} }
func (m *ImportRawKeyRequest) String() string { return proto.CompactTextString(m) }
func (*ImportRawKeyRequest) ProtoMessage()    {}
func (*ImportRawKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{25}
}

func (m *ImportRawKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportRawKeyRequest.Unmarshal(m, b)
}
func (m *ImportRawKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportRawKeyRequest.Marshal(b, m, deterministic)
}
func (m *ImportRawKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportRawKeyRequest.Merge(m, src)
}
func (m *ImportRawKeyRequest) XXX_Size() int {
	return xxx_messageInfo_ImportRawKeyRequest.Size(m)
}
func (m *ImportRawKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportRawKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImportRawKeyRequest proto.InternalMessageInfo

func (m *ImportRawKeyRequest) GetRawKey() string {
	if m != nil {
		return m.RawKey
	}
	return ""
}

func (m *ImportRawKeyRequest) GetNewAccountConfig() []byte {
	if m != nil {
		return m.NewAccountConfig
	}
	return nil
}

type ImportRawKeyResponse struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportRawKeyResponse) Reset()         { *m = ImportRawKeyResponse{} }
func (m *ImportRawKeyResponse) String() string { return proto.CompactTextString(m) }
func (*ImportRawKeyResponse) ProtoMessage()    {}
func (*ImportRawKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{26}
}

func (m *ImportRawKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportRawKeyResponse.Unmarshal(m, b)
}
func (m *ImportRawKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportRawKeyResponse.Marshal(b, m, deterministic)
}
func (m *ImportRawKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportRawKeyResponse.Merge(m, src)
}
func (m *ImportRawKeyResponse) XXX_Size() int {
	return xxx_messageInfo_ImportRawKeyResponse.Size(m)
}
func (m *ImportRawKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportRawKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ImportRawKeyResponse proto.InternalMessageInfo

func (m *ImportRawKeyResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.GetEventStreamResponse_Event", GetEventStreamResponse_Event_name, GetEventStreamResponse_Event_value)
	proto.RegisterType((*Account)(nil), "proto.Account")
	proto.RegisterType((*StatusRequest)(nil), "proto.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "proto.StatusResponse")
	proto.RegisterType((*OpenRequest)(nil), "proto.OpenRequest")
	proto.RegisterType((*OpenResponse)(nil), "proto.OpenResponse")
	proto.RegisterType((*CloseRequest)(nil), "proto.CloseRequest")
	proto.RegisterType((*CloseResponse)(nil), "proto.CloseResponse")
	proto.RegisterType((*AccountsRequest)(nil), "proto.AccountsRequest")
	proto.RegisterType((*AccountsResponse)(nil), "proto.AccountsResponse")
	proto.RegisterType((*ContainsRequest)(nil), "proto.ContainsRequest")
	proto.RegisterType((*ContainsResponse)(nil), "proto.ContainsResponse")
	proto.RegisterType((*SignHashRequest)(nil), "proto.SignHashRequest")
	proto.RegisterType((*SignHashResponse)(nil), "proto.SignHashResponse")
	proto.RegisterType((*SignTxRequest)(nil), "proto.SignTxRequest")
	proto.RegisterType((*SignTxResponse)(nil), "proto.SignTxResponse")
	proto.RegisterType((*SignHashWithPassphraseRequest)(nil), "proto.SignHashWithPassphraseRequest")
	proto.RegisterType((*SignTxWithPassphraseRequest)(nil), "proto.SignTxWithPassphraseRequest")
	proto.RegisterType((*GetEventStreamRequest)(nil), "proto.GetEventStreamRequest")
	proto.RegisterType((*GetEventStreamResponse)(nil), "proto.GetEventStreamResponse")
	proto.RegisterType((*TimedUnlockRequest)(nil), "proto.TimedUnlockRequest")
	proto.RegisterType((*TimedUnlockResponse)(nil), "proto.TimedUnlockResponse")
	proto.RegisterType((*LockRequest)(nil), "proto.LockRequest")
	proto.RegisterType((*LockResponse)(nil), "proto.LockResponse")
	proto.RegisterType((*NewAccountRequest)(nil), "proto.NewAccountRequest")
	proto.RegisterType((*NewAccountResponse)(nil), "proto.NewAccountResponse")
	proto.RegisterType((*ImportRawKeyRequest)(nil), "proto.ImportRawKeyRequest")
	proto.RegisterType((*ImportRawKeyResponse)(nil), "proto.ImportRawKeyResponse")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 866 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x6d, 0x6f, 0xe2, 0x46,
	0x10, 0xae, 0x21, 0x04, 0x32, 0x80, 0x71, 0x36, 0x84, 0x10, 0x27, 0xa9, 0xa2, 0x6d, 0x55, 0xa1,
	0xa8, 0x4d, 0x2a, 0xda, 0xa8, 0xaa, 0x22, 0xa5, 0x45, 0x01, 0xa5, 0x28, 0x28, 0x50, 0x43, 0x12,
	0xf5, 0x53, 0xe4, 0xc2, 0x36, 0x58, 0x75, 0x6c, 0x6a, 0x9b, 0x90, 0x7e, 0xb8, 0xdf, 0x71, 0xd2,
	0xfd, 0xa3, 0xfb, 0x57, 0x27, 0xdb, 0xe3, 0x77, 0x73, 0x82, 0xbb, 0xfb, 0x04, 0xfb, 0xcc, 0xdb,
	0xe3, 0xd9, 0xd9, 0x67, 0xa0, 0x2c, 0x8f, 0xc7, 0xfa, 0x5c, 0xb3, 0x4e, 0x67, 0x86, 0x6e, 0xe9,
	0x24, 0xe7, 0xfc, 0xd0, 0x73, 0xc8, 0xb7, 0x5c, 0x9c, 0xd4, 0x21, 0x2f, 0x4f, 0x26, 0x06, 0x33,
	0xcd, 0x3a, 0x77, 0xcc, 0x35, 0x4a, 0x92, 0x77, 0x24, 0x02, 0x64, 0xe7, 0x86, 0x5a, 0xcf, 0x1c,
	0x73, 0x8d, 0x2d, 0xc9, 0xfe, 0x4b, 0x7f, 0x80, 0xf2, 0xd0, 0x92, 0xad, 0xb9, 0x29, 0xb1, 0xff,
	0xe6, 0xcc, 0xb4, 0xc8, 0x21, 0x6c, 0x2d, 0x64, 0x55, 0x65, 0xd6, 0x9d, 0xa1, 0x3a, 0xe1, 0x5b,
	0x52, 0x00, 0xd0, 0x06, 0xf0, 0x9e, 0xbb, 0x39, 0xd3, 0x35, 0x93, 0x91, 0x1a, 0x6c, 0x9a, 0x0e,
	0x82, 0xce, 0x78, 0xa2, 0x37, 0x50, 0xec, 0xcf, 0x98, 0xb6, 0x52, 0x5a, 0xf2, 0x35, 0xc0, 0x4c,
	0x36, 0xcd, 0xd9, 0xd4, 0x90, 0x4d, 0x86, 0xf4, 0x42, 0x08, 0xe5, 0xa1, 0xe4, 0x26, 0x73, 0x8b,
	0xd2, 0xef, 0xa1, 0x74, 0xa5, 0xea, 0x26, 0x5b, 0x8d, 0x74, 0x05, 0xca, 0xe8, 0x8d, 0xe1, 0x67,
	0x50, 0xc1, 0x5e, 0xad, 0xf8, 0xd9, 0x97, 0x20, 0x04, 0x01, 0xf8, 0xe1, 0x27, 0x50, 0xc0, 0x8b,
	0xb0, 0x3f, 0x3d, 0xdb, 0x28, 0x36, 0x79, 0xf7, 0x46, 0x4e, 0xd1, 0x55, 0xf2, 0xed, 0xf4, 0x02,
	0x2a, 0x57, 0xba, 0x66, 0xc9, 0x8a, 0xe6, 0x17, 0x6c, 0x40, 0x1e, 0xcd, 0x4e, 0xb9, 0x64, 0xb4,
	0x67, 0xa6, 0x3f, 0x83, 0x10, 0x04, 0x63, 0xf1, 0x63, 0x28, 0x2a, 0x26, 0xa2, 0x6c, 0xe2, 0x64,
	0x28, 0x48, 0x61, 0x88, 0xf6, 0xa1, 0x32, 0x54, 0x9e, 0xb4, 0x3f, 0x64, 0x73, 0xba, 0x76, 0x49,
	0x42, 0x60, 0x63, 0x2a, 0x9b, 0x53, 0xe7, 0x26, 0x4a, 0x92, 0xf3, 0x9f, 0x9e, 0x80, 0x10, 0x24,
	0x0c, 0x2e, 0xdf, 0x60, 0xe6, 0x5c, 0xb5, 0x70, 0xd0, 0xf0, 0x44, 0x15, 0x28, 0xdb, 0xbe, 0xa3,
	0xd7, 0xf5, 0x4b, 0x57, 0x21, 0x67, 0xa8, 0xb3, 0xd1, 0x2b, 0xd6, 0x76, 0x0f, 0xf6, 0x48, 0x8f,
	0xa7, 0xb2, 0xa2, 0x75, 0xdb, 0xf5, 0xac, 0x3b, 0xd2, 0x78, 0xa4, 0xdf, 0x01, 0xef, 0x95, 0x42,
	0x52, 0x7e, 0x06, 0x2e, 0x94, 0x81, 0xbe, 0x81, 0x23, 0x8f, 0xfe, 0x83, 0x62, 0x4d, 0x07, 0xfe,
	0x70, 0x7d, 0x91, 0xee, 0xc4, 0x26, 0x38, 0x9b, 0x98, 0xe0, 0xb7, 0x1c, 0x1c, 0xb8, 0x3c, 0x3f,
	0xb7, 0xfa, 0x9a, 0x0d, 0x8a, 0x31, 0xdb, 0x48, 0x30, 0xdb, 0x83, 0xdd, 0x6b, 0x66, 0x75, 0x5e,
	0x98, 0x66, 0x0d, 0x2d, 0x83, 0xc9, 0xcf, 0x48, 0x89, 0xbe, 0xe7, 0xa0, 0x16, 0xb7, 0x60, 0x8b,
	0x7f, 0x85, 0x1c, 0xb3, 0x61, 0x87, 0x2b, 0xdf, 0xfc, 0x06, 0xb9, 0xa6, 0x7b, 0x9f, 0x3a, 0x98,
	0xe4, 0x46, 0x44, 0x1f, 0x5a, 0x26, 0xfe, 0xd0, 0xee, 0x21, 0xe7, 0x78, 0x13, 0x02, 0xfc, 0x43,
	0xab, 0xd7, 0xeb, 0x8c, 0x1e, 0x5b, 0x92, 0xd4, 0xbd, 0xef, 0xb4, 0x85, 0xaf, 0xc8, 0x36, 0x94,
	0x11, 0xeb, 0x0f, 0x3a, 0xb7, 0x9d, 0xb6, 0xc0, 0x85, 0xdc, 0xda, 0x52, 0x7f, 0x30, 0xe8, 0xb4,
	0x85, 0x8c, 0x8d, 0x0d, 0x7a, 0x77, 0xd7, 0xdd, 0xdb, 0xc7, 0xe1, 0xa8, 0x25, 0x8d, 0x3a, 0x6d,
	0x21, 0x4b, 0x5f, 0x80, 0x8c, 0x94, 0x67, 0x36, 0xb9, 0xd3, 0x54, 0x7d, 0xfc, 0xef, 0xfa, 0x4d,
	0x17, 0xa1, 0x60, 0xb7, 0x6c, 0xa1, 0x1b, 0x13, 0x24, 0xed, 0x9f, 0x6d, 0xdb, 0x64, 0x6e, 0xc8,
	0x96, 0xa2, 0x6b, 0x4e, 0xef, 0xb3, 0x92, 0x7f, 0xa6, 0xbb, 0xb0, 0x13, 0xa9, 0x8b, 0x02, 0xf4,
	0x0b, 0x14, 0x7b, 0x9f, 0xc2, 0xc3, 0x16, 0xc2, 0x5e, 0x38, 0xd1, 0x6f, 0xb0, 0x7d, 0xcb, 0x16,
	0x9e, 0x1b, 0xa6, 0x3b, 0x01, 0x41, 0xf3, 0xc1, 0x2b, 0x5d, 0xfb, 0x47, 0x79, 0xc2, 0xb7, 0x90,
	0xc0, 0xe9, 0x25, 0x90, 0x70, 0x02, 0xbc, 0xdf, 0xd5, 0x09, 0xfd, 0x05, 0x3b, 0xdd, 0xe7, 0x99,
	0x6e, 0x58, 0x92, 0xbc, 0xb8, 0x61, 0xff, 0x7b, 0x14, 0x6c, 0x61, 0x70, 0x00, 0x6f, 0x2b, 0xb8,
	0xa7, 0x54, 0x6a, 0x99, 0x25, 0xd4, 0x7e, 0x87, 0x6a, 0x34, 0xf5, 0xba, 0xe4, 0x9a, 0xef, 0xf2,
	0xc0, 0x23, 0x38, 0x64, 0xc6, 0x8b, 0x32, 0x66, 0xe4, 0x1c, 0x36, 0xdd, 0x05, 0x46, 0xaa, 0x18,
	0x15, 0x59, 0x7f, 0xe2, 0x6e, 0x0c, 0xc5, 0x9a, 0x67, 0xb0, 0x61, 0x2f, 0x20, 0x42, 0xd0, 0x1c,
	0x5a, 0x6d, 0xe2, 0x4e, 0x04, 0xc3, 0x80, 0x26, 0xe4, 0x9c, 0x9d, 0x43, 0x3c, 0x6b, 0x78, 0x5f,
	0x89, 0xd5, 0x28, 0x88, 0x31, 0x17, 0x50, 0xf0, 0xb6, 0x0c, 0xa9, 0x45, 0xbf, 0xc9, 0xe7, 0xb7,
	0x97, 0xc0, 0x83, 0x60, 0x6f, 0x4b, 0xf8, 0xc1, 0xb1, 0x9d, 0xe3, 0x07, 0x27, 0xd6, 0xc9, 0x05,
	0x14, 0x3c, 0x71, 0xf4, 0x83, 0x63, 0xdb, 0xc3, 0x0f, 0x4e, 0x2c, 0x01, 0xbb, 0xa5, 0x8e, 0xb2,
	0x05, 0x2d, 0x0d, 0x6b, 0x7f, 0xd0, 0xd2, 0xa8, 0x4c, 0x3f, 0x40, 0x2d, 0x5d, 0x90, 0xc9, 0xb7,
	0xb1, 0x4a, 0xa9, 0x8a, 0xb9, 0x9c, 0xcf, 0x9f, 0x50, 0x4d, 0x53, 0x5a, 0x42, 0x23, 0x3c, 0xd2,
	0x93, 0x2e, 0xe1, 0xda, 0x07, 0x3e, 0xaa, 0x6d, 0xe4, 0x70, 0x89, 0xe4, 0xb9, 0x69, 0x8e, 0x3e,
	0x2a, 0x88, 0x3f, 0x72, 0xa4, 0x0d, 0xc5, 0x90, 0x2e, 0x90, 0x7d, 0xf4, 0x4f, 0x6a, 0x94, 0x28,
	0xa6, 0x99, 0x82, 0xa9, 0xb4, 0xd5, 0xc0, 0x9f, 0xca, 0x90, 0xa6, 0xf8, 0x53, 0x19, 0x96, 0x0b,
	0xd2, 0x02, 0x08, 0x5e, 0x3b, 0xa9, 0xa3, 0x4b, 0x42, 0x41, 0xc4, 0xfd, 0x14, 0x0b, 0xa6, 0xb8,
	0x86, 0x52, 0xf8, 0x55, 0x12, 0x8f, 0x5f, 0x8a, 0x0a, 0x88, 0x07, 0xa9, 0x36, 0x37, 0xd1, 0xdf,
	0x9b, 0x8e, 0xed, 0xa7, 0x0f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xef, 0xca, 0x54, 0xcf, 0x0a,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenResponse, error)
	Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error)
	Accounts(ctx context.Context, in *AccountsRequest, opts ...grpc.CallOption) (*AccountsResponse, error)
	Contains(ctx context.Context, in *ContainsRequest, opts ...grpc.CallOption) (*ContainsResponse, error)
	SignHash(ctx context.Context, in *SignHashRequest, opts ...grpc.CallOption) (*SignHashResponse, error)
	SignTx(ctx context.Context, in *SignTxRequest, opts ...grpc.CallOption) (*SignTxResponse, error)
	SignHashWithPassphrase(ctx context.Context, in *SignHashWithPassphraseRequest, opts ...grpc.CallOption) (*SignHashResponse, error)
	SignTxWithPassphrase(ctx context.Context, in *SignTxWithPassphraseRequest, opts ...grpc.CallOption) (*SignTxResponse, error)
	GetEventStream(ctx context.Context, in *GetEventStreamRequest, opts ...grpc.CallOption) (AccountService_GetEventStreamClient, error)
	TimedUnlock(ctx context.Context, in *TimedUnlockRequest, opts ...grpc.CallOption) (*TimedUnlockResponse, error)
	Lock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockResponse, error)
	NewAccount(ctx context.Context, in *NewAccountRequest, opts ...grpc.CallOption) (*NewAccountResponse, error)
	ImportRawKey(ctx context.Context, in *ImportRawKeyRequest, opts ...grpc.CallOption) (*ImportRawKeyResponse, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountService/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenResponse, error) {
	out := new(OpenResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountService/Open", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error) {
	out := new(CloseResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountService/Close", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Accounts(ctx context.Context, in *AccountsRequest, opts ...grpc.CallOption) (*AccountsResponse, error) {
	out := new(AccountsResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountService/Accounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Contains(ctx context.Context, in *ContainsRequest, opts ...grpc.CallOption) (*ContainsResponse, error) {
	out := new(ContainsResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountService/Contains", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) SignHash(ctx context.Context, in *SignHashRequest, opts ...grpc.CallOption) (*SignHashResponse, error) {
	out := new(SignHashResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountService/SignHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) SignTx(ctx context.Context, in *SignTxRequest, opts ...grpc.CallOption) (*SignTxResponse, error) {
	out := new(SignTxResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountService/SignTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) SignHashWithPassphrase(ctx context.Context, in *SignHashWithPassphraseRequest, opts ...grpc.CallOption) (*SignHashResponse, error) {
	out := new(SignHashResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountService/SignHashWithPassphrase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) SignTxWithPassphrase(ctx context.Context, in *SignTxWithPassphraseRequest, opts ...grpc.CallOption) (*SignTxResponse, error) {
	out := new(SignTxResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountService/SignTxWithPassphrase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetEventStream(ctx context.Context, in *GetEventStreamRequest, opts ...grpc.CallOption) (AccountService_GetEventStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AccountService_serviceDesc.Streams[0], "/proto.AccountService/GetEventStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &accountServiceGetEventStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AccountService_GetEventStreamClient interface {
	Recv() (*GetEventStreamResponse, error)
	grpc.ClientStream
}

type accountServiceGetEventStreamClient struct {
	grpc.ClientStream
}

func (x *accountServiceGetEventStreamClient) Recv() (*GetEventStreamResponse, error) {
	m := new(GetEventStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *accountServiceClient) TimedUnlock(ctx context.Context, in *TimedUnlockRequest, opts ...grpc.CallOption) (*TimedUnlockResponse, error) {
	out := new(TimedUnlockResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountService/TimedUnlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Lock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockResponse, error) {
	out := new(LockResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountService/Lock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) NewAccount(ctx context.Context, in *NewAccountRequest, opts ...grpc.CallOption) (*NewAccountResponse, error) {
	out := new(NewAccountResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountService/NewAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ImportRawKey(ctx context.Context, in *ImportRawKeyRequest, opts ...grpc.CallOption) (*ImportRawKeyResponse, error) {
	out := new(ImportRawKeyResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountService/ImportRawKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	Open(context.Context, *OpenRequest) (*OpenResponse, error)
	Close(context.Context, *CloseRequest) (*CloseResponse, error)
	Accounts(context.Context, *AccountsRequest) (*AccountsResponse, error)
	Contains(context.Context, *ContainsRequest) (*ContainsResponse, error)
	SignHash(context.Context, *SignHashRequest) (*SignHashResponse, error)
	SignTx(context.Context, *SignTxRequest) (*SignTxResponse, error)
	SignHashWithPassphrase(context.Context, *SignHashWithPassphraseRequest) (*SignHashResponse, error)
	SignTxWithPassphrase(context.Context, *SignTxWithPassphraseRequest) (*SignTxResponse, error)
	GetEventStream(*GetEventStreamRequest, AccountService_GetEventStreamServer) error
	TimedUnlock(context.Context, *TimedUnlockRequest) (*TimedUnlockResponse, error)
	Lock(context.Context, *LockRequest) (*LockResponse, error)
	NewAccount(context.Context, *NewAccountRequest) (*NewAccountResponse, error)
	ImportRawKey(context.Context, *ImportRawKeyRequest) (*ImportRawKeyResponse, error)
}

// UnimplementedAccountServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServiceServer struct {
}

func (*UnimplementedAccountServiceServer) Status(ctx context.Context, req *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (*UnimplementedAccountServiceServer) Open(ctx context.Context, req *OpenRequest) (*OpenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Open not implemented")
}
func (*UnimplementedAccountServiceServer) Close(ctx context.Context, req *CloseRequest) (*CloseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Close not implemented")
}
func (*UnimplementedAccountServiceServer) Accounts(ctx context.Context, req *AccountsRequest) (*AccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Accounts not implemented")
}
func (*UnimplementedAccountServiceServer) Contains(ctx context.Context, req *ContainsRequest) (*ContainsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Contains not implemented")
}
func (*UnimplementedAccountServiceServer) SignHash(ctx context.Context, req *SignHashRequest) (*SignHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignHash not implemented")
}
func (*UnimplementedAccountServiceServer) SignTx(ctx context.Context, req *SignTxRequest) (*SignTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignTx not implemented")
}
func (*UnimplementedAccountServiceServer) SignHashWithPassphrase(ctx context.Context, req *SignHashWithPassphraseRequest) (*SignHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignHashWithPassphrase not implemented")
}
func (*UnimplementedAccountServiceServer) SignTxWithPassphrase(ctx context.Context, req *SignTxWithPassphraseRequest) (*SignTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignTxWithPassphrase not implemented")
}
func (*UnimplementedAccountServiceServer) GetEventStream(req *GetEventStreamRequest, srv AccountService_GetEventStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetEventStream not implemented")
}
func (*UnimplementedAccountServiceServer) TimedUnlock(ctx context.Context, req *TimedUnlockRequest) (*TimedUnlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TimedUnlock not implemented")
}
func (*UnimplementedAccountServiceServer) Lock(ctx context.Context, req *LockRequest) (*LockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lock not implemented")
}
func (*UnimplementedAccountServiceServer) NewAccount(ctx context.Context, req *NewAccountRequest) (*NewAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewAccount not implemented")
}
func (*UnimplementedAccountServiceServer) ImportRawKey(ctx context.Context, req *ImportRawKeyRequest) (*ImportRawKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportRawKey not implemented")
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountService/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Open_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Open(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountService/Open",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Open(ctx, req.(*OpenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountService/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Close(ctx, req.(*CloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Accounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Accounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountService/Accounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Accounts(ctx, req.(*AccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Contains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Contains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountService/Contains",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Contains(ctx, req.(*ContainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_SignHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).SignHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountService/SignHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).SignHash(ctx, req.(*SignHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_SignTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).SignTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountService/SignTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).SignTx(ctx, req.(*SignTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_SignHashWithPassphrase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignHashWithPassphraseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).SignHashWithPassphrase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountService/SignHashWithPassphrase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).SignHashWithPassphrase(ctx, req.(*SignHashWithPassphraseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_SignTxWithPassphrase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignTxWithPassphraseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).SignTxWithPassphrase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountService/SignTxWithPassphrase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).SignTxWithPassphrase(ctx, req.(*SignTxWithPassphraseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetEventStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetEventStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AccountServiceServer).GetEventStream(m, &accountServiceGetEventStreamServer{stream})
}

type AccountService_GetEventStreamServer interface {
	Send(*GetEventStreamResponse) error
	grpc.ServerStream
}

type accountServiceGetEventStreamServer struct {
	grpc.ServerStream
}

func (x *accountServiceGetEventStreamServer) Send(m *GetEventStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _AccountService_TimedUnlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimedUnlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).TimedUnlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountService/TimedUnlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).TimedUnlock(ctx, req.(*TimedUnlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Lock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Lock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountService/Lock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Lock(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_NewAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).NewAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountService/NewAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).NewAccount(ctx, req.(*NewAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ImportRawKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportRawKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ImportRawKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountService/ImportRawKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ImportRawKey(ctx, req.(*ImportRawKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _AccountService_Status_Handler,
		},
		{
			MethodName: "Open",
			Handler:    _AccountService_Open_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _AccountService_Close_Handler,
		},
		{
			MethodName: "Accounts",
			Handler:    _AccountService_Accounts_Handler,
		},
		{
			MethodName: "Contains",
			Handler:    _AccountService_Contains_Handler,
		},
		{
			MethodName: "SignHash",
			Handler:    _AccountService_SignHash_Handler,
		},
		{
			MethodName: "SignTx",
			Handler:    _AccountService_SignTx_Handler,
		},
		{
			MethodName: "SignHashWithPassphrase",
			Handler:    _AccountService_SignHashWithPassphrase_Handler,
		},
		{
			MethodName: "SignTxWithPassphrase",
			Handler:    _AccountService_SignTxWithPassphrase_Handler,
		},
		{
			MethodName: "TimedUnlock",
			Handler:    _AccountService_TimedUnlock_Handler,
		},
		{
			MethodName: "Lock",
			Handler:    _AccountService_Lock_Handler,
		},
		{
			MethodName: "NewAccount",
			Handler:    _AccountService_NewAccount_Handler,
		},
		{
			MethodName: "ImportRawKey",
			Handler:    _AccountService_ImportRawKey_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEventStream",
			Handler:       _AccountService_GetEventStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "account.proto",
}
